# Generated by Django 2.1.5 on 2019-01-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashcode', models.CharField(max_length=20, verbose_name='Hash Code')),
                ('original_link', models.CharField(max_length=255, verbose_name='Link')),
            ],
            options={
                'db_table': 'link',
            },
        ),
    ]
