# Generated by Django 2.1.5 on 2019-01-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('len_hash', models.IntegerField(verbose_name='Hash Lenght')),
            ],
            options={
                'db_table': 'param',
            },
        ),
    ]
