# Generated by Django 2.1.5 on 2019-01-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0002_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='original_link',
            field=models.CharField(max_length=500, verbose_name='Link'),
        ),
    ]
